### ISSUE TITLE
Bbpress - Comments - missing translations

### ISSUE THREAD

**Issue by suport001** [opradu/newspaper#317]
![bbpress](https://cloud.githubusercontent.com/assets/6737313/4403504/16840cda-44a4-11e4-96d1-65b792d86c32.png)
![comments](https://cloud.githubusercontent.com/assets/6737313/4403520/541c660a-44a4-11e4-9b6c-7495c5eedebf.png)

**Comment by opradu** [comment]
will be fixed in newspaper 5 - no more custom bbpress templates
