### ISSUE TITLE
Missing translation - If you're not happy with the results, please do another search

### ISSUE THREAD

**Issue by suport001** [opradu/newspaper#550]
![image](https://cloud.githubusercontent.com/assets/6737313/5996849/f75b90cc-aab9-11e4-8f9c-2ff575e0be84.png)

**Comment by nicugergely** [comment]
S-a rezolvat prin update in partea de server - td_admin
In tema, trebuie modificat in td_translations.php

<div class="td-box-row">
            <div class="td-box-description">
                <span class="td-box-title td-title-on-row"><?php echo $key;?></span>
                <p></p>
            </div>
            <div class="td-box-control-full">
                <?php
                echo td_panel_generator::input(array(
                    'ds' => 'td_translate',
                    'option_id' => $key,
                    'placeholder' => $value
                ));
                ?>
            </div>
        </div>

cu 


<div class="td-box-row">
            <div class="td-box-description">
                <span class="td-box-title td-title-on-row"><?php echo $key;?></span>
                <p></p>
            </div>
            <div class="td-box-control-full">
                <?php
                echo td_panel_generator::input(array(
                    'ds' => 'td_translate',
                    'option_id' => $key_id,
                    'placeholder' => $value
                ));
                ?>
            </div>
        </div>
